<?xml version="1.0"?>

<!--
  CS22B1090
  Shubh Khandelwal
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="CYLINDER" params="link_density link_length link_material link_name link_radius">
    <link name="${link_name}">
      <visual>
        <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${link_length}" radius="${link_radius}"/>
        </geometry>
        <material name="${link_material}"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${link_length}" radius="${link_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${link_density * 3.142 * link_radius * link_radius * link_length}"/>
        <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
        <inertia
        ixx="${(3.142 / 12.0) * (3 * link_radius * link_radius + link_length * link_length) * link_radius * link_radius * link_length * link_density}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(3.142 / 12.0) * (3 * link_radius * link_radius + link_length * link_length) * link_radius * link_radius * link_length * link_density}"
        iyz="0.0"
        izz="${(3.142 / 2.0) * link_radius * link_radius * link_radius * link_radius * link_length * link_density}"
        />
      </inertial>
    </link>
  </xacro:macro>

</robot>