<?xml version="1.0"?>

<!--
  CS22B1090
  Shubh Khandelwal
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="SPHERE" params="link_centre link_density link_material link_name link_radius">
    <link name="${link_name}">
      <visual>
        <origin xyz="0 0 ${link_centre}" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${link_radius}"/>
        </geometry>
        <material name="${link_material}"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${link_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${link_density * (4.0 * 3.142 / 3.0) * link_radius * link_radius * link_radius}"/>
        <origin xyz="0 0 ${link_centre}" rpy="0 0 0"/>
        <inertia
        ixx="${(8 * 3.142 / 15.0) * link_radius * link_radius * link_radius * link_radius * link_radius * link_density}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(8 * 3.142 / 15.0) * link_radius * link_radius * link_radius * link_radius * link_radius * link_density}"
        iyz="0.0"
        izz="${(8 * 3.142 / 15.0) * link_radius * link_radius * link_radius * link_radius * link_radius * link_density}"
        />
      </inertial>
    </link>
  </xacro:macro>

</robot>